### ISSUE TITLE
10.x Support - No longer hooking?

### ISSUE THREAD

**Issue by agnosticlines** [roblabla/GhiDracula-Ext#2]
Hey there,

This is an awesome extension, I've been trying to get something similar working for a while. It works fine on 9.2 but it stopped working sometime around version 10, do you still use this and if so could you provide the patch locations needed to get it working?

I suck at Java but I had a quick look around and it seems to be the GTable and GCell renderer classes are no longer being hooked?

Not sure why that'd happen, the class definitions are in tact, there's no stack trace or anything when hooking.

Not too sure but would love to keep using this on 10.x.

To be specific, it still does hook some things and work, however the tables used in things such as the script manager or xrefs have their original gradient pattern, not sure if it's to do with the swapping colour option, but I tried disabling that and it still didn't work.

Thanks!

**Comment by roblabla** [comment]
Release 0.0.3 (currently building) should fix the issue.
